fixing layer issue
for fixing:
File "C:\Users\shamovich\PycharmProjects\citygml-enrichment-tool\CityEnrich_enrichment.py", line 540, in EnrichmentStart
    if (entry == None or pd.isna(entry)) and not (non_LDT_defaults[i] == None or pd.isna(non_LDT_defaults[i])):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

caused by list of layers